//! Link-code generator. Builds memorable `<adjective>-<word>-<noun>`
//! handles per locale so users can dictate a code to a friend out
//! loud. Word lists ported verbatim from
//! `tango/src/randomcode.rs`; cross-locale sampling simplified
//! (legacy used reservoir sampling for a one-of-N pick, which is
//! overkill when N is tiny).

use rand::Rng;
use std::sync::LazyLock;

struct Choices {
    pub starts: &'static [&'static str],
    pub middles: &'static [&'static str],
    pub ends: &'static [&'static str],
}

static CHOICES: LazyLock<std::collections::HashMap<&'static str, Choices>> = LazyLock::new(|| {
    std::collections::HashMap::from([
        (
            "en",
            Choices {
                starts: &[
                    "648",
                    "abd",
                    "adjective",
                    "agameof",
                    "alpha",
                    "anti",
                    "availableto",
                    "awfullyhot",
                    "awhisperof",
                    "bad",
                    "balanced",
                    "baolongji",
                    "beholdthe",
                    "better",
                    "beyondard",
                    "big",
                    "bingussed",
                    "blind",
                    "boneless",
                    "boosted",
                    "bottom",
                    "bubbly",
                    "bugged",
                    "caidou",
                    "central",
                    "chilly",
                    "chonky",
                    "cobbing",
                    "code",
                    "cold",
                    "compiled",
                    "cool",
                    "corny",
                    "cursed",
                    "dancing",
                    "dang",
                    "dark",
                    "deleted",
                    "dianboren",
                    "diannaoren",
                    "dianqiuji",
                    "dunpaishenti",
                    "electric",
                    "endless",
                    "epic",
                    "error",
                    "famous",
                    "feedthe",
                    "feifacundang",
                    "fistfullof",
                    "flying",
                    "free",
                    "gege",
                    "ghostly",
                    "giga",
                    "goodluck",
                    "harbingerof",
                    "heavy",
                    "hello",
                    "helpme",
                    "herecomes",
                    "herecomes",
                    "higsbys",
                    "hikari",
                    "hot",
                    "hyper",
                    "illegalsave",
                    "im",
                    "impossible",
                    "infamous",
                    "intense",
                    "invisible",
                    "itsme",
                    "jackin",
                    "jiangkou",
                    "jinzhi",
                    "juda",
                    "kuajie",
                    "lacking",
                    "legsgo",
                    "lets",
                    "licenseto",
                    "lookup",
                    "lucky",
                    "lv100",
                    "mega",
                    "moon",
                    "murkland",
                    "murky",
                    "nebula",
                    "net",
                    "new",
                    "nice",
                    "nicebig",
                    "no",
                    "nonstop",
                    "official",
                    "old",
                    "one",
                    "online",
                    "open",
                    "overwhelming",
                    "player",
                    "pocketfullof",
                    "poggy",
                    "pomabu",
                    "popped",
                    "protect",
                    "quanmianfangyu",
                    "rad",
                    "relaxed",
                    "returnof",
                    "revengeofthe",
                    "risen",
                    "risky",
                    "running",
                    "ryuuseimanager",
                    "scary",
                    "shashouren",
                    "shining",
                    "shrimpy",
                    "spectacular",
                    "spiffy",
                    "spooky",
                    "starforce",
                    "stolen",
                    "sus",
                    "sword",
                    "team",
                    "techno",
                    "the",
                    "thefinal",
                    "thesearchfor",
                    "thicc",
                    "thick",
                    "throwthe",
                    "tiantianduizhan",
                    "tongbu",
                    "top",
                    "totallyaccurate",
                    "tuolier",
                    "unhinged",
                    "unlikely",
                    "uwu",
                    "verbing",
                    "veteran",
                    "vibing",
                    "weili",
                    "weird",
                    "whohere",
                    "winking",
                    "xinghe",
                    "yitiantiande",
                    "yoinky",
                    "zhuyi",
                ],
                middles: &[
                    "airhockey",
                    "airraid",
                    "airshot",
                    "airspin",
                    "alpaca",
                    "alpha",
                    "antidmg",
                    "antinavi",
                    "antirecov",
                    "antisword",
                    "anubis",
                    "apple",
                    "aquadrgn",
                    "aquasword",
                    "areagrab",
                    "assnsword",
                    "aurahead",
                    "baby",
                    "balance",
                    "balanced",
                    "bambsword",
                    "barrier",
                    "bass",
                    "bassanly",
                    "bcc",
                    "bdt",
                    "bigbomb",
                    "bighook",
                    "billy",
                    "bingus",
                    "blackbomb",
                    "blast",
                    "blues",
                    "bogos",
                    "bombcorn",
                    "bomboy",
                    "boomer",
                    "boyfriends",
                    "browser",
                    "brs",
                    "bubble",
                    "bubbleman",
                    "bugbomb",
                    "bugfix",
                    "bugfrag",
                    "bunny",
                    "burrito",
                    "busterup",
                    "cannon",
                    "cannot",
                    "canodumb",
                    "cat",
                    "charge",
                    "chicken",
                    "chiptrader",
                    "chonk",
                    "circlegun",
                    "circles",
                    "circus",
                    "cob",
                    "coffeepot",
                    "colarmy",
                    "coldbear",
                    "coldman",
                    "colonel",
                    "colorpoint",
                    "command",
                    "content",
                    "cornshot",
                    "cowboy",
                    "crackshot",
                    "crossdivide",
                    "cucumber",
                    "damage",
                    "damnswrd",
                    "daniel",
                    "digeridoo",
                    "discord",
                    "dive",
                    "dog",
                    "dollthunder",
                    "donut",
                    "doubleshot",
                    "drcossak",
                    "drillarm",
                    "duo",
                    "dust",
                    "eguchi",
                    "eleball",
                    "elec",
                    "elecdrgb",
                    "elecpulse",
                    "elecsword",
                    "element",
                    "elemtrap",
                    "energybomb",
                    "erase",
                    "error",
                    "falzar",
                    "fan",
                    "fanfare",
                    "fastgauge",
                    "firebrn",
                    "firehit",
                    "firesword",
                    "fish",
                    "fishanly",
                    "flashbomb",
                    "friday",
                    "fullcust",
                    "geddon",
                    "golemhit",
                    "grabbanish",
                    "gregar",
                    "ground",
                    "guardian",
                    "gundels",
                    "havefun",
                    "heat",
                    "hiboomer",
                    "holypanel",
                    "hub",
                    "hubbatch",
                    "humor",
                    "ice",
                    "iceball",
                    "iceseed",
                    "imfish",
                    "iminthecode",
                    "invisible",
                    "ironshell",
                    "judge",
                    "justiceone",
                    "lan",
                    "lance",
                    "landing",
                    "lifeaura",
                    "lifesync",
                    "lilboiler",
                    "machgun",
                    "magcoil",
                    "magnum",
                    "ryuuseimanager",
                ],
                ends: &[
                    "6",
                    "aaaaaa",
                    "alpha",
                    "amogus",
                    "angy",
                    "applm",
                    "area",
                    "aura",
                    "banned",
                    "battle",
                    "beastmode",
                    "beedited",
                    "bianji",
                    "bimbus",
                    "bingus",
                    "binted",
                    "blessing",
                    "blubblub",
                    "bot",
                    "burrito",
                    "bushenghuole",
                    "chip",
                    "chonked",
                    "chulong",
                    "clowntown",
                    "cob",
                    "cobbers",
                    "combo",
                    "congratulations",
                    "cornfusion",
                    "cornout",
                    "crasher",
                    "damn",
                    "data",
                    "delete",
                    "denizen",
                    "eguchiwut",
                    "endofstring",
                    "energy",
                    "error",
                    "exe",
                    "execute",
                    "experience",
                    "extra",
                    "faked",
                    "fangyu",
                    "fartspin",
                    "forme",
                    "fortnite",
                    "frenzy",
                    "gauntlet",
                    "ggswp",
                    "goutoupao",
                    "grandprix",
                    "greatplay",
                    "hamachi",
                    "heehoo",
                    "helpimtrappedinhere",
                    "hour",
                    "huh",
                    "hype",
                    "impression",
                    "isa",
                    "isbalanced",
                    "issue",
                    "iswinning",
                    "jello",
                    "legabed",
                    "letmeout",
                    "license",
                    "lilguy",
                    "loicense",
                    "longsword",
                    "lovemegaman",
                    "man",
                    "megalegs",
                    "meme",
                    "miekun",
                    "milk",
                    "minna",
                    "moi",
                    "mojo",
                    "nebulajoy",
                    "occurroico",
                    "omega",
                    "parttwo",
                    "party",
                    "pause",
                    "power",
                    "powerhour",
                    "progchamp",
                    "programadvance",
                    "ratioed",
                    "reg",
                    "rollback",
                    "ronghe",
                    "rotango",
                    "ryuuseimanager",
                    "sfboy",
                    "shanchu",
                    "shmooving",
                    "shuibuzhao",
                    "sickos",
                    "slimetier",
                    "snapped",
                    "solution",
                    "sp",
                    "spam",
                    "sploinky",
                    "sprite",
                    "stevejobs",
                    "strategy",
                    "swag",
                    "swaggums",
                    "swarm",
                    "symeseus",
                    "tag",
                    "tech",
                    "technology",
                    "tfc",
                    "thunder",
                    "tier",
                    "tiltcontrols",
                    "time",
                    "tongbu",
                    "toptier",
                    "trill",
                    "ultrafiesta",
                    "unchained",
                    "uninstalled",
                    "unlegs",
                    "uwu",
                    "vbalink",
                    "victor",
                    "wansui",
                    "wavedash",
                    "wswalk",
                    "wuguandongxi",
                    "x2",
                    "yeastmode",
                    "yeet",
                    "youareworthy",
                    "yourewinner",
                    "yum",
                ],
            },
        ),
        (
            "ja",
            Choices {
                starts: &[
                    "abunai",
                    "anoo",
                    "biyondaaru",
                    "bokuno",
                    "dareka",
                    "daakuchippu",
                    "haroharo",
                    "hazimete",
                    "hikari",
                    "hontouno",
                    "hoshikawa",
                    "ii",
                    "intaanetto",
                    "itiban",
                    "mada",
                    "maji",
                    "makenai",
                    "masaka",
                    "meta",
                    "mettya",
                    "metyakuyta",
                    "minna",
                    "muzukasii",
                    "mou",
                    "naisu",
                    "nee",
                    "ohayou",
                    "oreno",
                    "ryuuseimanager",
                    "sakurai",
                    "sasuga",
                    "sausage",
                    "shinkurochippu",
                    "singuru",
                    "sugee",
                    "sugoi",
                    "sugu",
                    "tasikani",
                    "tokorode",
                    "toriaezu",
                    "toripuru",
                    "toriru",
                    "tuyoi",
                    "tuyosugiru",
                    "wagahaiha",
                    "yahari",
                    "yoi",
                    "yorosiku",
                    "zannen",
                    "zenzen",
                    "zibunno",
                    "zituwa",
                ],
                middles: &[
                    "adokore",
                    "arigatou",
                    "basutaa",
                    "batoru",
                    "dekao",
                    "dhuuo",
                    "doyoubi",
                    "eguti",
                    "eguze",
                    "faruzaa",
                    "furusinkuro",
                    "enzan",
                    "hontounotikara",
                    "geemu",
                    "guranpuri",
                    "gureiga",
                    "iiwake",
                    "ikkai",
                    "kasutamu",
                    "kasutamaizaa",
                    "kayoubi",
                    "kimoti",
                    "koonpaathii",
                    "koonsyotto",
                    "mainkurafuto",
                    "masutazukurasu",
                    "meiru",
                    "meizin",
                    "mondai",
                    "neko",
                    "netto",
                    "nige",
                    "nontan",
                    "onegai",
                    "rokkuman",
                    "ryuuseimanager",
                    "saito",
                    "siniakurasu",
                    "subaru",
                    "surottoin",
                    "susi",
                    "sutegapanesuti",
                    "syoubu",
                    "taisen",
                    "tango",
                    "tengu",
                    "tikara",
                    "tisao",
                    "tyouzetu",
                    "waburuwiisuto",
                    "wairi",
                    "wotsukainasai",
                ],
                ends: &[
                    "bakari",
                    "daizyoubu",
                    "dake",
                    "dearu",
                    "derito",
                    "desu",
                    "faito",
                    "gogogo",
                    "gozaimasu",
                    "hazimemasite",
                    "hazu",
                    "ikanai",
                    "ikenai",
                    "itadakimasu",
                    "kasutamaizu",
                    "kudasai",
                    "kure",
                    "kurosufushyuujon",
                    "kusa",
                    "makenai",
                    "maketa",
                    "miseteyaro",
                    "mitetekure",
                    "nai",
                    "onegai",
                    "oomaigaa",
                    "ryuuseimanager",
                    "sikatanai",
                    "simasu",
                    "simasyou",
                    "sitteruno",
                    "sugee",
                    "sugiru",
                    "sukanai",
                    "syouganai",
                    "taisen",
                    "taisensimasyou",
                    "tasukete",
                    "tenkyuu",
                    "tigau",
                    "tsuyokunaritaindarou",
                    "uwaa",
                    "wakaranai",
                    "warota",
                    "yabe",
                    "yaritai",
                    "yaritakunai",
                    "yaru",
                    "yatta",
                    "ze",
                    "zyanai",
                ],
            },
        ),
        // (
        //     "es",
        //     Choices {
        //         starts: &[
        //             "bassado",
        //             "hay",
        //             "hombre",
        //             "jugadorzero",
        //             "mi",
        //             "orgullosamente",
        //             "princessa",
        //             "reskek",
        //             "serenito",
        //             "sospechoso",
        //             "usando",
        //         ],
        //         middles: &[
        //             "alguien", "bn3", "es", "estillo", "jueves", "roca", "mandalo", "mi",
        //             "pride", "ribbita",
        //         ],
        //         ends: &[
        //             "adios",
        //             "brazil",
        //             "chiposcuro",
        //             "detras",
        //             "ejecutable",
        //             "ejecucao",
        //             "facha",
        //             "meta",
        //             "vainilla",
        //         ],
        //     }
        // )
    ])
});

pub fn generate(lang: &unic_langid::LanguageIdentifier) -> String {
    let mut thread_rng = rand::thread_rng();

    let mut lang_code = lang.language.as_str();
    if !CHOICES.contains_key(&lang_code) {
        lang_code = "en";
    }

    // 1-in-5 we pull from a different locale for variety. Pick a
    // random non-current locale by sampling an index from the
    // filtered key set.
    if thread_rng.gen_range(0..5) == 0 {
        let others: Vec<&'static str> = CHOICES.keys().copied().filter(|k| *k != lang_code).collect();
        if !others.is_empty() {
            lang_code = others[thread_rng.gen_range(0..others.len())];
        }
    }

    let choices = CHOICES.get(lang_code).unwrap();
    format!(
        "{}-{}-{}",
        choices.starts[thread_rng.gen_range(0..choices.starts.len())],
        choices.middles[thread_rng.gen_range(0..choices.middles.len())],
        choices.ends[thread_rng.gen_range(0..choices.ends.len())]
    )
}
