name = "tango-signaling-server"
main = "src/index.ts"
compatibility_date = "2026-05-11"

[[durable_objects.bindings]]
name = "MATCHMAKING"
class_name = "MatchmakingHub"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["MatchmakingHub"]

route = "matchmakingcn.trill.workers.dev"
