# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: signaling.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'signaling.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fsignaling.proto\x12\x0ftango.signaling\"\xc2\x06\n\x06Packet\x12.\n\x05hello\x18\x04 \x01(\x0b\x32\x1d.tango.signaling.Packet.HelloH\x00\x12.\n\x05start\x18\x01 \x01(\x0b\x32\x1d.tango.signaling.Packet.StartH\x00\x12.\n\x05offer\x18\x02 \x01(\x0b\x32\x1d.tango.signaling.Packet.OfferH\x00\x12\x30\n\x06\x61nswer\x18\x03 \x01(\x0b\x32\x1e.tango.signaling.Packet.AnswerH\x00\x12.\n\x05\x61\x62ort\x18\x05 \x01(\x0b\x32\x1d.tango.signaling.Packet.AbortH\x00\x12,\n\x04ping\x18\x06 \x01(\x0b\x32\x1c.tango.signaling.Packet.PingH\x00\x1a\xac\x01\n\x05Hello\x12<\n\x0bice_servers\x18\x01 \x03(\x0b\x32\'.tango.signaling.Packet.Hello.ICEServer\x1a\x65\n\tICEServer\x12\x17\n\ncredential\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x15\n\x08username\x18\x02 \x01(\tH\x01\x88\x01\x01\x12\x0c\n\x04urls\x18\x03 \x03(\tB\r\n\x0b_credentialB\x0b\n\t_username\x1aK\n\x05Start\x12\x18\n\x10protocol_version\x18\x01 \x01(\r\x12\x11\n\toffer_sdp\x18\x02 \x01(\t\x12\x15\n\rconnection_id\x18\x03 \x01(\x0c\x1a\x14\n\x05Offer\x12\x0b\n\x03sdp\x18\x01 \x01(\t\x1a\x15\n\x06\x41nswer\x12\x0b\n\x03sdp\x18\x01 \x01(\t\x1a\xdd\x01\n\x05\x41\x62ort\x12\x34\n\x06reason\x18\x01 \x01(\x0e\x32$.tango.signaling.Packet.Abort.Reason\"\x9d\x01\n\x06Reason\x12\x12\n\x0eREASON_UNKNOWN\x10\x00\x12#\n\x1fREASON_PROTOCOL_VERSION_TOO_OLD\x10\x01\x12#\n\x1fREASON_PROTOCOL_VERSION_TOO_NEW\x10\x02\x12\x1d\n\x19REASON_MISSING_SESSION_ID\x10\x03\x12\x16\n\x12REASON_NOT_UPGRADE\x10\x04\x1a\x06\n\x04PingB\x07\n\x05whichb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'signaling_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PACKET']._serialized_start=37
  _globals['_PACKET']._serialized_end=871
  _globals['_PACKET_HELLO']._serialized_start=336
  _globals['_PACKET_HELLO']._serialized_end=508
  _globals['_PACKET_HELLO_ICESERVER']._serialized_start=407
  _globals['_PACKET_HELLO_ICESERVER']._serialized_end=508
  _globals['_PACKET_START']._serialized_start=510
  _globals['_PACKET_START']._serialized_end=585
  _globals['_PACKET_OFFER']._serialized_start=587
  _globals['_PACKET_OFFER']._serialized_end=607
  _globals['_PACKET_ANSWER']._serialized_start=609
  _globals['_PACKET_ANSWER']._serialized_end=630
  _globals['_PACKET_ABORT']._serialized_start=633
  _globals['_PACKET_ABORT']._serialized_end=854
  _globals['_PACKET_ABORT_REASON']._serialized_start=697
  _globals['_PACKET_ABORT_REASON']._serialized_end=854
  _globals['_PACKET_PING']._serialized_start=856
  _globals['_PACKET_PING']._serialized_end=862
# @@protoc_insertion_point(module_scope)
